package legend.game.submap;

public enum SubmapMediaState {
  LOAD_SHADOW_AND_RESET_LIGHTING_0,
  LOAD_MUSIC_1,
  WAIT_FOR_MUSIC_2,
  LOAD_EFFECT_TEXTURES_3,
  LOAD_EFFECT_MODELS_4,
  LOAD_SOBJ_ASSETS_AND_SCRIPTS_5,
  WAIT_FOR_SOBJ_ASSETS_AND_SCRIPTS_6,
  PREPARE_TO_LOAD_SUBMAP_MODEL_7,
  LOAD_SUBMAP_MODEL_8,
  FINALIZE_SUBMAP_LOADING_9,
  DONE,
}
