#!/bin/bash

if [[ -d ./jdk21 ]]
then
  rm -rf ./jdk21
fi

echo Downloading java...
mkdir "jdk21"
curl -s -L "https://corretto.aws/downloads/resources/21.0.6.7.1/amazon-corretto-21.0.6.7.1-@os@-@arch@.tar.gz" | tar -vxz -C jdk21 --strip-components=1
