#!/bin/bash

JAVA=./jdk/bin/java

if [[ ! -f $JAVA ]]
then
  ./download-java
fi

"$JAVA" -cp "lod-game-@version@.jar:libs/*" legend.game.Main -Xmx2G -ea -Djoml.fastmath -Djoml.sinLookup -Djoml.useMathFma
