package legend.game.inventory;

public enum WhichMenu {
  NONE_0,

  INIT_INVENTORY_MENU_1,
  WAIT_FOR_MUSIC_TO_LOAD_AND_LOAD_S_ITEM_2,

  RENDER_INVENTORY_MENU_4,
  UNLOAD_INVENTORY_MENU_5,

  INIT_SHOP_MENU_6,
  RENDER_SHOP_MENU_9,
  UNLOAD_SHOP_MENU_10,

  INIT_CAMPAIGN_SELECTION_MENU,
  RENDER_CAMPAIGN_SELECTION_MENU,
  UNLOAD_CAMPAIGN_SELECTION_MENU,

  INIT_SAVE_GAME_MENU_16,
  RENDER_SAVE_GAME_MENU_19,
  UNLOAD_SAVE_GAME_MENU_20,

  INIT_CHAR_SWAP_MENU_21,
  RENDER_CHAR_SWAP_MENU_24,
  UNLOAD_CHAR_SWAP_MENU_25,

  INIT_POST_COMBAT_REPORT_26,
  WAIT_FOR_POST_COMBAT_REPORT_MUSIC_TO_LOAD_AND_LOAD_S_ITEM_27,

  RENDER_POST_COMBAT_REPORT_29,
  UNLOAD_POST_COMBAT_REPORT_30,

  INIT_TOO_MANY_ITEMS_MENU_31,
  RENDER_TOO_MANY_ITEMS_MENU_34,
  UNLOAD_TOO_MANY_ITEMS_MENU_35,

  RENDER_SHOP_CARRIED_ITEMS_36,

  INIT_NEW_CAMPAIGN_MENU,
  RENDER_NEW_CAMPAIGN_MENU,
  UNLOAD_NEW_CAMPAIGN_MENU,

  INIT_OPTIONS_MENU,
  RENDER_OPTIONS_MENU,
  UNLOAD_OPTIONS_MENU,

  INIT_CATEGORIZE_SAVE_MENU,
  RENDER_CATEGORIZE_SAVE_MENU,
  UNLOAD_CATEGORIZE_SAVE_MENU,

  INIT_MEMCARD_MENU,
  RENDER_MEMCARD_MENU,
  UNLOAD_MEMCARD_MENU,

  QUIT,
}
