package legend.core;
import legend.core.platform.input.InputAction;
import legend.core.platform.input.InputActionRegistry;
import legend.core.platform.input.InputActionRegistryEvent;
import legend.game.EngineStateType;
import legend.game.EngineStateTypeRegistry;
import legend.game.RegisterEngineStateTypesEvent;
import legend.game.additions.Addition;
import legend.game.additions.AdditionRegistry;
import legend.game.additions.AdditionRegistryEvent;
import legend.game.characters.CharacterTemplate;
import legend.game.characters.CharacterTemplateRegistry;
import legend.game.characters.Element;
import legend.game.characters.ElementRegistry;
import legend.game.characters.ElementRegistryEvent;
import legend.game.characters.LevelUpAction;
import legend.game.characters.LevelUpActionRegistry;
import legend.game.characters.RegisterCharacterTemplatesEvent;
import legend.game.characters.RegisterLevelUpActionsEvent;
import legend.game.characters.StatModType;
import legend.game.characters.StatModTypeRegistry;
import legend.game.characters.StatModTypeRegistryEvent;
import legend.game.characters.StatType;
import legend.game.characters.StatTypeRegistry;
import legend.game.characters.StatTypeRegistryEvent;
import legend.game.combat.bent.BattleEntityType;
import legend.game.combat.bent.BattleEntityTypeRegistry;
import legend.game.combat.bent.BattleEntityTypeRegistryEvent;
import legend.game.combat.bent.ElementIcon;
import legend.game.combat.bent.ElementIconRegistry;
import legend.game.combat.bent.ElementIconRegistryEvent;
import legend.game.combat.deff.DeffPackage;
import legend.game.combat.deff.DeffRegistry;
import legend.game.combat.deff.RegisterDeffsEvent;
import legend.game.combat.encounters.Encounter;
import legend.game.combat.encounters.EncounterRegistry;
import legend.game.combat.encounters.EncounterRegistryEvent;
import legend.game.combat.postbattleactions.PostBattleAction;
import legend.game.combat.postbattleactions.PostBattleActionRegistry;
import legend.game.combat.postbattleactions.RegisterPostBattleActionsEvent;
import legend.game.combat.ui.BattleAction;
import legend.game.combat.ui.BattleActionRegistry;
import legend.game.combat.ui.RegisterBattleActionsEvent;
import legend.game.inventory.Equipment;
import legend.game.inventory.EquipmentRegistry;
import legend.game.inventory.EquipmentRegistryEvent;
import legend.game.inventory.Good;
import legend.game.inventory.GoodsRegistry;
import legend.game.inventory.GoodsRegistryEvent;
import legend.game.inventory.Item;
import legend.game.inventory.ItemRegistry;
import legend.game.inventory.ItemRegistryEvent;
import legend.game.inventory.ShopRegistry;
import legend.game.inventory.ShopRegistryEvent;
import legend.game.inventory.SpellRegistry;
import legend.game.inventory.SpellRegistryEvent;
import legend.game.inventory.SpellStats0c;
import legend.game.saves.CampaignType;
import legend.game.saves.CampaignTypeRegistry;
import legend.game.saves.ConfigEntry;
import legend.game.saves.ConfigRegistry;
import legend.game.saves.ConfigRegistryEvent;
import legend.game.saves.RegisterCampaignTypesEvent;
import legend.game.types.Shop;
import legend.game.wmap.registries.RegisterWorldMapAvatarsEvent;
import legend.game.wmap.registries.RegisterWorldMapBehavioursEvent;
import legend.game.wmap.registries.RegisterWorldMapCoolonDestinationsEvent;
import legend.game.wmap.registries.RegisterWorldMapEncounterPoolsEvent;
import legend.game.wmap.registries.RegisterWorldMapGeometryEvent;
import legend.game.wmap.registries.RegisterWorldMapNodesEvent;
import legend.game.wmap.registries.RegisterWorldMapPlacesEvent;
import legend.game.wmap.registries.RegisterWorldMapPortalsEvent;
import legend.game.wmap.registries.RegisterWorldMapPresentationProfilesEvent;
import legend.game.wmap.registries.RegisterWorldMapRoutesEvent;
import legend.game.wmap.registries.RegisterWorldMapStoryPresetsEvent;
import legend.game.wmap.registries.RegisterWorldMapTeleportLinksEvent;
import legend.game.wmap.registries.WorldMapAvatarEntry;
import legend.game.wmap.registries.WorldMapAvatarRegistry;
import legend.game.wmap.registries.WorldMapBehaviourRegistry;
import legend.game.wmap.registries.WorldMapCoolonDestinationEntry;
import legend.game.wmap.registries.WorldMapCoolonDestinationRegistry;
import legend.game.wmap.registries.WorldMapEncounterPoolEntry;
import legend.game.wmap.registries.WorldMapEncounterPoolRegistry;
import legend.game.wmap.registries.WorldMapGeometryEntry;
import legend.game.wmap.registries.WorldMapGeometryRegistry;
import legend.game.wmap.registries.WorldMapNodeEntry;
import legend.game.wmap.registries.WorldMapNodeRegistry;
import legend.game.wmap.registries.WorldMapPlaceEntry;
import legend.game.wmap.registries.WorldMapPlaceRegistry;
import legend.game.wmap.registries.WorldMapPortalEntry;
import legend.game.wmap.registries.WorldMapPortalRegistry;
import legend.game.wmap.registries.WorldMapPresentationProfileEntry;
import legend.game.wmap.registries.WorldMapPresentationProfileRegistry;
import legend.game.wmap.registries.WorldMapRouteEntry;
import legend.game.wmap.registries.WorldMapRouteRegistry;
import legend.game.wmap.registries.WorldMapStoryPresetEntry;
import legend.game.wmap.registries.WorldMapStoryPresetRegistry;
import legend.game.wmap.registries.WorldMapTeleportLinkEntry;
import legend.game.wmap.registries.WorldMapTeleportLinkRegistry;
import legend.game.wmap.world.WorldMapBehaviour;
import org.legendofdragoon.modloader.events.EventManager;
import org.legendofdragoon.modloader.events.registries.RegistryEvent;
import org.legendofdragoon.modloader.registries.MutableRegistry;
import org.legendofdragoon.modloader.registries.Registry;
import org.legendofdragoon.modloader.registries.RegistryEntry;

import java.util.function.Consumer;
import java.util.function.Function;

public class Registries extends org.legendofdragoon.modloader.registries.Registries {
  public final Registry<CampaignType> campaignTypes = this.addRegistry(new CampaignTypeRegistry(), RegisterCampaignTypesEvent::new);
  public final Registry<EngineStateType<?>> engineStateTypes = this.addRegistry(new EngineStateTypeRegistry(), RegisterEngineStateTypesEvent::new);
  public final Registry<InputAction> inputActions = this.addRegistry(new InputActionRegistry(), InputActionRegistryEvent::new);
  public final Registry<CharacterTemplate> characterTemplates = this.addRegistry(new CharacterTemplateRegistry(), RegisterCharacterTemplatesEvent::new);
  public final Registry<LevelUpAction<?>> levelUpActions = this.addRegistry(new LevelUpActionRegistry(), RegisterLevelUpActionsEvent::new);
  public final Registry<StatType<?>> statTypes = this.addRegistry(new StatTypeRegistry(), StatTypeRegistryEvent::new);
  public final Registry<StatModType<?, ?, ?>> statModTypes = this.addRegistry(new StatModTypeRegistry(), StatModTypeRegistryEvent::new);
  public final Registry<Element> elements = this.addRegistry(new ElementRegistry(), ElementRegistryEvent::new);
  public final Registry<BattleEntityType> battleEntityTypes = this.addRegistry(new BattleEntityTypeRegistry(), BattleEntityTypeRegistryEvent::new);
  public final Registry<Item> items = this.addRegistry(new ItemRegistry(), ItemRegistryEvent::new);
  public final Registry<Equipment> equipment = this.addRegistry(new EquipmentRegistry(), EquipmentRegistryEvent::new);
  public final Registry<Good> goods = this.addRegistry(new GoodsRegistry(), GoodsRegistryEvent::new);
  public final Registry<Shop> shop = this.addRegistry(new ShopRegistry(), ShopRegistryEvent::new);
  public final Registry<SpellStats0c> spells = this.addRegistry(new SpellRegistry(), SpellRegistryEvent::new);
  public final Registry<ConfigEntry<?>> config = this.addRegistry(new ConfigRegistry(), ConfigRegistryEvent::new);
  public final Registry<DeffPackage> deff = this.addRegistry(new DeffRegistry(), RegisterDeffsEvent::new);
  public final Registry<Encounter> encounters = this.addRegistry(new EncounterRegistry(), EncounterRegistryEvent::new);
  public final Registry<Addition> additions = this.addRegistry(new AdditionRegistry(), AdditionRegistryEvent::new);
  public final Registry<BattleAction> battleActions = this.addRegistry(new BattleActionRegistry(), RegisterBattleActionsEvent::new);
  public final Registry<PostBattleAction<?, ?>> postBattleActions = this.addRegistry(new PostBattleActionRegistry(), RegisterPostBattleActionsEvent::new);
  public final Registry<ElementIcon> elementIcons = this.addRegistry(new ElementIconRegistry(), ElementIconRegistryEvent::new);

  public final Registry<WorldMapNodeEntry> worldMapNodes = this.addRegistry(new WorldMapNodeRegistry(), RegisterWorldMapNodesEvent::new);
  public final Registry<WorldMapGeometryEntry> worldMapGeometry = this.addRegistry(new WorldMapGeometryRegistry(), RegisterWorldMapGeometryEvent::new);
  public final Registry<WorldMapAvatarEntry> worldMapAvatars = this.addRegistry(new WorldMapAvatarRegistry(), RegisterWorldMapAvatarsEvent::new);
  public final Registry<WorldMapRouteEntry> worldMapRoutes = this.addRegistry(new WorldMapRouteRegistry(), RegisterWorldMapRoutesEvent::new);
  public final Registry<WorldMapPlaceEntry> worldMapPlaces = this.addRegistry(new WorldMapPlaceRegistry(), RegisterWorldMapPlacesEvent::new);
  public final Registry<WorldMapPortalEntry> worldMapPortals = this.addRegistry(new WorldMapPortalRegistry(), RegisterWorldMapPortalsEvent::new);

  public final Registry<WorldMapStoryPresetEntry> worldMapStoryPresets = this.addRegistry(new WorldMapStoryPresetRegistry(), RegisterWorldMapStoryPresetsEvent::new);
  public final Registry<WorldMapCoolonDestinationEntry> worldMapCoolonDestinations = this.addRegistry(new WorldMapCoolonDestinationRegistry(), RegisterWorldMapCoolonDestinationsEvent::new);
  public final Registry<WorldMapTeleportLinkEntry> worldMapTeleportLinks = this.addRegistry(new WorldMapTeleportLinkRegistry(), RegisterWorldMapTeleportLinksEvent::new);
  public final Registry<WorldMapEncounterPoolEntry> worldMapEncounterPools = this.addRegistry(new WorldMapEncounterPoolRegistry(), RegisterWorldMapEncounterPoolsEvent::new);
  public final Registry<WorldMapPresentationProfileEntry> worldMapPresentationProfiles = this.addRegistry(new WorldMapPresentationProfileRegistry(), RegisterWorldMapPresentationProfilesEvent::new);
  public final Registry<WorldMapBehaviour> worldMapBehaviours = this.addRegistry(new WorldMapBehaviourRegistry(), RegisterWorldMapBehavioursEvent::new);

  protected Registries(final EventManager events, final Consumer<Access> access) {
    super(events, access);
  }

  @Override
  protected <Type extends RegistryEntry> Registry<Type> addRegistry(final Registry<Type> registry, final Function<MutableRegistry<Type>, RegistryEvent.Register<Type>> registryEvent) {
    return super.addRegistry(registry, registryEvent);
  }
}
