package legend.game.input;

public enum InputKeyCode {
  NOT_SET,
  BUTTON_NORTH,
  BUTTON_SOUTH,
  BUTTON_EAST,
  BUTTON_WEST,

  BUTTON_CENTER_1,
  BUTTON_CENTER_2,
  BUTTON_THUMB_1,
  BUTTON_THUMB_2,
  BUTTON_SHOULDER_LEFT_1,
  BUTTON_SHOULDER_LEFT_2,
  BUTTON_SHOULDER_RIGHT_1,
  BUTTON_SHOULDER_RIGHT_2,

  DPAD_UP,
  DPAD_DOWN,
  DPAD_LEFT,
  DPAD_RIGHT,

  JOYSTICK_LEFT_X,
  JOYSTICK_LEFT_Y,
  JOYSTICK_LEFT_BUTTON_UP,
  JOYSTICK_LEFT_BUTTON_DOWN,
  JOYSTICK_LEFT_BUTTON_LEFT,
  JOYSTICK_LEFT_BUTTON_RIGHT,


  JOYSTICK_RIGHT_X,
  JOYSTICK_RIGHT_Y,

  JOYSTICK_RIGHT_BUTTON_UP,
  JOYSTICK_RIGHT_BUTTON_DOWN,
  JOYSTICK_RIGHT_BUTTON_LEFT,
  JOYSTICK_RIGHT_BUTTON_RIGHT,

  INPUT_ANY_ACTIVITY,
}
