package legend.game.types;

/// Text can influence control flow
/// Scripts can influence control flow
public enum TextboxTextState {
  UNINITIALIZED_0,
  INIT_TEXTBOX_TYPE_1,
  SET_STATE_PROCESS_TEXT_2,
  SPECIAL_SELECTION_BOUNDARY_CONDITION_SCRIPT_ONLY_3,
  PROCESS_TEXT_4,
  SCROLL_TEXT_5,
  WAIT_FOR_INPUT_ADVANCED_DIRTY_BOX_6,
  PROCESS_INPUT_ADVANCED_7,
  WAIT_FOR_PAUSE_8,
  SCROLL_TEXT_DOWN_9,
  SCROLL_TEXT_UP_10,
  WAIT_FOR_INPUT_ADVANCED_CLEAN_BOX_11,
  CHECK_UNINITIALIZED_PENDING_INPUT_12,
  PROCESS_NO_INPUT_ADVANCED_13,
  TICK_TIMER_SMAP_NO_INPUT_ADVANCED_14,
  CLOSE_TEXTBOX_15,
  CLOSE_BATTLE_NO_INPUT_16,
  IGNORE_SCROLL_LINE_BREAK_17,
  PROCESS_STATE_TRANSITION_18,
  TICK_STATE_TRANSITION_TIMER_19,
  HANDLE_SCROLL_UP_20,
  HANDLE_SCROLL_DOWN_21,
  SELECTION_22,
  TRANSITION_AFTER_TIMEOUT_23,
}
