package legend.game.sound;

public class ReverbConfig {
  public final int dApf1;
  public final int dApf2;
  public final int vIir;
  public final int vComb1;
  public final int vComb2;
  public final int vComb3;
  public final int vComb4;
  public final int vWall;
  public final int vApf1;
  public final int vApf2;
  public final int mLSame;
  public final int mRSame;
  public final int mLComb1;
  public final int mRComb1;
  public final int mLComb2;
  public final int mRComb2;
  public final int dLSame;
  public final int dRSame;
  public final int mLDiff;
  public final int mRDiff;
  public final int mLComb3;
  public final int mRComb3;
  public final int mLComb4;
  public final int mRComb4;
  public final int dLDiff;
  public final int dRDiff;
  public final int mLApf1;
  public final int mRApf1;
  public final int mLApf2;
  public final int mRApf2;
  public final int vLIn;
  public final int vRIn;

  public ReverbConfig(final int dApf1, final int dApf2, final int vIir, final int vComb1, final int vComb2, final int vComb3, final int vComb4, final int vWall, final int vApf1, final int vApf2, final int mLSame, final int mRSame, final int mLComb1, final int mRComb1, final int mLComb2, final int mRComb2, final int dLSame, final int dRSame, final int mLDiff, final int mRDiff, final int mLComb3, final int mRComb3, final int mLComb4, final int mRComb4, final int dLDiff, final int dRDiff, final int mLApf1, final int mRApf1, final int mLApf2, final int mRApf2, final int vLIn, final int vRIn) {
    this.dApf1 = dApf1;
    this.dApf2 = dApf2;
    this.vIir = vIir;
    this.vComb1 = vComb1;
    this.vComb2 = vComb2;
    this.vComb3 = vComb3;
    this.vComb4 = vComb4;
    this.vWall = vWall;
    this.vApf1 = vApf1;
    this.vApf2 = vApf2;
    this.mLSame = mLSame;
    this.mRSame = mRSame;
    this.mLComb1 = mLComb1;
    this.mRComb1 = mRComb1;
    this.mLComb2 = mLComb2;
    this.mRComb2 = mRComb2;
    this.dLSame = dLSame;
    this.dRSame = dRSame;
    this.mLDiff = mLDiff;
    this.mRDiff = mRDiff;
    this.mLComb3 = mLComb3;
    this.mRComb3 = mRComb3;
    this.mLComb4 = mLComb4;
    this.mRComb4 = mRComb4;
    this.dLDiff = dLDiff;
    this.dRDiff = dRDiff;
    this.mLApf1 = mLApf1;
    this.mRApf1 = mRApf1;
    this.mLApf2 = mLApf2;
    this.mRApf2 = mRApf2;
    this.vLIn = vLIn;
    this.vRIn = vRIn;
  }
}
