package legend.core.spu;

import legend.core.audio.GenericSource;
import legend.core.audio.sequencer.Reverberizer;
import legend.game.modding.coremod.CoreMod;
import legend.game.sound.ReverbConfig;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Marker;
import org.apache.logging.log4j.MarkerManager;
import org.lwjgl.system.MemoryUtil;

import static legend.core.GameEngine.AUDIO_THREAD;
import static legend.core.GameEngine.CONFIG;
import static legend.core.audio.Constants.BASE_SAMPLE_RATE;
import static legend.core.audio.Constants.PITCH_BIT_SHIFT;
import static org.lwjgl.openal.AL10.AL_FORMAT_STEREO16;

public class Spu {
  private static final Logger LOGGER = LogManager.getFormatterLogger(Spu.class);
  private static final Marker SPU_MARKER = MarkerManager.getMarker("SPU");
  private static final Marker SPU_KEY_MARKER = MarkerManager.getMarker("SPU_KEY");

  private final Reverberizer reverberizer = new Reverberizer();
  public final Voice[] voices = new Voice[24];

  private float playerVolume = 1.0f;
  private float mainVolumeL;
  private float mainVolumeR;
  private long keyOn;
  private long keyOff;
  private long channelFmMode;
  private long channelNoiseMode;
  private long channelReverbMode;
  private final NoiseGenerator noiseGenerator = new NoiseGenerator();
  private boolean reverbEnabled;
  private boolean muted = true;

  public Spu() {
    for(int i = 0; i < this.voices.length; i++) {
      this.voices[i] = new Voice(i);
    }

    for(int i = 0; i < interpolationWeights.length; i++) {
      final double pow1 = i / (double)interpolationWeights.length;
      final double pow2 = pow1 * pow1;
      final double pow3 = pow2 * pow1;

      interpolationWeights[i] = new float[] {
        (float)(0.5d * (-pow3 + 2 * pow2 - pow1)),
        (float)(0.5d * (3 * pow3 - 5 * pow2 + 2)),
        (float)(0.5d * (-3 * pow3 + 4 * pow2 + pow1)),
        (float)(0.5d * (pow3 - pow2))
      };
    }

    for(int i = 0; i < sampleRates.length; i++) {
      sampleRates[i] = (int)Math.round((1L << PITCH_BIT_SHIFT) * (44100d / 48000d) * Math.pow(2, i / (double)sampleRates.length));
    }
  }

  public void setPlayerVolume(final float volume) {
    this.playerVolume = volume;
  }

  public void tick(final long sampleData, final long samplePosition) {
    float sumLeft = 0;
    float sumRight = 0;

    float sumLeftReverb = 0;
    float sumRightReverb = 0;

    final long edgeKeyOn = this.keyOn;
    final long edgeKeyOff = this.keyOff;
    this.keyOn = 0;
    this.keyOff = 0;

    if(edgeKeyOn != 0) {
      LOGGER.debug(SPU_MARKER, "Keying on %x", edgeKeyOn);
    }

    if(edgeKeyOff != 0) {
      LOGGER.debug(SPU_MARKER, "Keying off %x", edgeKeyOff);
    }

    this.noiseGenerator.tick();

    for(int voiceIndex = 0; voiceIndex < this.voices.length; voiceIndex++) {
      final Voice v = this.voices[voiceIndex];

      //keyOn and KeyOff are edge triggered on 0 to 1
      if((edgeKeyOn & 0x1L << voiceIndex) != 0) {
        LOGGER.debug(SPU_MARKER, "Keying on voice %d", voiceIndex);
        v.keyOn();
      }

      if((edgeKeyOff & 0x1L << voiceIndex) != 0) {
        LOGGER.debug(SPU_MARKER, "Keying off voice %d", voiceIndex);
        v.keyOff();
      }

      if(v.adsrPhase == Phase.Off) {
        v.latest = 0;
        continue;
      }

      float sample;
      if((this.channelNoiseMode & 0x1L << voiceIndex) == 0) {
        sample = this.sampleVoice(voiceIndex);
      } else {
        //Generated by tickNoiseGenerator
        sample = this.noiseGenerator.volumeF;
      }

      //Handle ADSR Envelope
      sample = (sample * v.adsrVolume) / 0x8000;
      v.tickAdsr();

      //Save sample for possible pitch modulation
      v.latest = sample;

      //Sum each voice sample
      if(!this.muted) {
        sumLeft += (sample * v.processVolume(v.volumeLeft)) / 0x8000;
        sumRight += (sample * v.processVolume(v.volumeRight)) / 0x8000;
      }

      if((this.channelReverbMode & 0x1L << voiceIndex) != 0) {
        sumLeftReverb += (sample * v.processVolume(v.volumeLeft)) / 0x8000;
        sumRightReverb += (sample * v.processVolume(v.volumeRight)) / 0x8000;
      }
    }

    this.reverberizer.processReverb(sumLeftReverb, sumRightReverb);

    sumLeft += this.reverberizer.getOutputLeft();
    sumRight += this.reverberizer.getOutputRight();

    //Clamp sum
    sumLeft = sumLeft * this.mainVolumeL;
    sumRight = sumRight * this.mainVolumeR;

    MemoryUtil.memPutFloat(sampleData + samplePosition * 8, sumLeft * this.playerVolume);
    MemoryUtil.memPutFloat(sampleData + 4 + samplePosition * 8, sumRight * this.playerVolume);
  }

  private float sampleVoice(final int v) {
    final Voice voice = this.voices[v];

    //Decode samples if its empty / next block
    if(!voice.hasSamples) {
      voice.decodeSamples();
      voice.hasSamples = true;

      final byte flags = this.voices[v].spuAdpcm[1];
      final boolean loopStart = (flags & 0x4) != 0;

      if(loopStart) {
        assert voice.currentAddress >= 0 : "Negative address";
        voice.adpcmRepeatAddress = voice.currentAddress;
      }
    }

    //Get indices for gauss interpolation
    final int interpolationIndex = voice.counter.getSampleInterpolationIndex();
    final int sampleIndex = voice.counter.getCurrentSampleIndex();

    //Interpolate latest samples
    //this is why the latest 3 samples from the last block are saved because if index is 0
    //any subtraction is gonna be oob of the current voice adpcm array

    final float[] weights = interpolationWeights[interpolationIndex];

    float interpolated;
    interpolated = weights[0] * voice.getSample(sampleIndex - 3);
    interpolated += weights[1] * voice.getSample(sampleIndex - 2);
    interpolated += weights[2] * voice.getSample(sampleIndex - 1);
    interpolated += weights[3] * voice.getSample(sampleIndex);

    //Pitch modulation: Starts at voice 1 as it needs the last voice
    long step = voice.pitch;
    if(v > 0 && (this.channelFmMode & 0x1L << v) != 0) {
      final float factor = this.voices[v - 1].latest + 1; //From previous voice
      step = Math.round(step * factor);
    }

    step = Math.min(step, 4L << PITCH_BIT_SHIFT);

    if(voice.counter.add(step)) {
      //Beyond the current adpcm sample block prepare to decode next
      voice.currentAddress += 2;
      voice.hasSamples = false;

      //LoopEnd and LoopRepeat flags are set after the "current block" set them as it's finished
      final byte flags = this.voices[v].spuAdpcm[1];
      final boolean loopEnd = (flags & 0x1) != 0;
      final boolean loopRepeat = (flags & 0x2) != 0;

      if(loopEnd) {
        if(loopRepeat) {
          voice.currentAddress = voice.adpcmRepeatAddress;
        } else {
          voice.adsrPhase = Phase.Off;
          voice.adsrVolume = 0;
        }
      }
    }

    return interpolated;
  }

  public void setMainVolume(final int left, final int right) {
    LOGGER.info(SPU_MARKER, "Setting SPU main volume to %04x, %04x", left, right);

    synchronized(Spu.class) {
      this.mainVolumeL = left / (float)0x8000;
      this.mainVolumeR = right / (float)0x8000;
    }
  }

  public int getMainVolumeLeft() {
    synchronized(Spu.class) {
      return Math.round(this.mainVolumeL * 0x8000);
    }
  }

  public int getMainVolumeRight() {
    synchronized(Spu.class) {
      return Math.round(this.mainVolumeR * 0x8000);
    }
  }

  public void setReverbVolume(final int left, final int right) {
    LOGGER.info(SPU_MARKER, "Setting SPU reverb volume to %04x, %04x", left, right);

    synchronized(Spu.class) {
      this.reverberizer.setVolume(left / (float)0x8000, right / (float)0x8000);
    }
  }

  public void keyOff(final long voices) {
    LOGGER.debug(SPU_KEY_MARKER, "Setting SPU key off to %08x", voices);

    synchronized(Spu.class) {
      this.keyOff |= voices;
    }
  }

  public void keyOn(final long voices) {
    LOGGER.debug(SPU_KEY_MARKER, "Setting SPU key on to %08x", voices);

    synchronized(Spu.class) {
      this.keyOn |= voices;
    }
  }

  public void clearKeyOn() {
    LOGGER.info(SPU_MARKER, "Clearing SPU key on");

    synchronized(Spu.class) {
      this.keyOn = 0;
    }
  }

  public void setNoiseMode(final long noiseMode) {
//    LOGGER.debug(SPU_MARKER, "Setting SPU noise mode to %x", noiseMode);

    synchronized(Spu.class) {
      this.channelNoiseMode = noiseMode;
    }
  }

  public void setReverbMode(final long reverbMode) {
//    LOGGER.debug(SPU_MARKER, "Setting SPU reverb mode to %x", reverbMode);

    synchronized(Spu.class) {
      this.channelReverbMode = reverbMode;
    }
  }

  public void setReverb(final int config) {
    synchronized(Spu.class) {
      this.reverberizer.setConfig(config);
    }
  }

  public void mute() {
    LOGGER.info(SPU_MARKER, "Muting SPU");

    synchronized(Spu.class) {
      this.muted = true;
    }
  }

  public void unmute() {
    LOGGER.info(SPU_MARKER, "Unmuting SPU");

    synchronized(Spu.class) {
      this.muted = false;
    }
  }

  public void enableReverb() {
    LOGGER.info(SPU_MARKER, "Enabling SPU reverb");

    synchronized(Spu.class) {
      this.reverbEnabled = true;
    }
  }

  public void disableReverb() {
    LOGGER.info(SPU_MARKER, "Disabling SPU reverb");

    synchronized(Spu.class) {
      this.reverbEnabled = false;
    }
  }

  public void setNoiseFrequency(final int packed) {
    LOGGER.info(SPU_MARKER, "Setting SPU noise frequency %x", packed);

    synchronized(Spu.class) {
      this.noiseGenerator.load(packed);
    }
  }

  private static final float[][] interpolationWeights = new float[512][];
  public static final int[] sampleRates = new int[768];
}
