package legend.lodmod;

import legend.core.GameEngine;
import legend.game.inventory.ShopRegistryEvent;
import legend.game.types.ShopStruct40;
import org.legendofdragoon.modloader.registries.Registrar;
import org.legendofdragoon.modloader.registries.RegistryDelegate;

import java.util.function.Supplier;

public final class LodShops {
  private LodShops() { }

  private static final Registrar<ShopStruct40, ShopRegistryEvent> SHOP_REGISTRAR = new Registrar<>(GameEngine.REGISTRIES.shop, LodMod.MOD_ID);

  public static final RegistryDelegate<ShopStruct40> BALE_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("bale_equipment_shop", () -> new ShopStruct40(0, LodEquipment.BASTARD_SWORD::get, LodEquipment.SPARKLE_ARROW::get, LodEquipment.SCALE_ARMOR::get, LodEquipment.LEATHER_JACKET::get, LodEquipment.SALLET::get, LodEquipment.POISON_GUARD::get, LodEquipment.PANIC_GUARD::get, LodEquipment.STUN_GUARD::get, LodEquipment.BRAVERY_AMULET::get, LodEquipment.KNIGHT_SHIELD::get));
  public static final RegistryDelegate<ShopStruct40> SERDIO_ITEM_SHOP = SHOP_REGISTRAR.register("serdio_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.SPEAR_FROST::get, LodItems.METEOR_FALL::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> LOHAN_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("lohan_equipment_shop", () -> new ShopStruct40(0, LodEquipment.LANCE::get, LodEquipment.CAPE::get, LodEquipment.LEGEND_CASQUE::get, LodEquipment.ACTIVE_RING::get, LodEquipment.PROTECTOR::get, LodEquipment.PANIC_GUARD::get, LodEquipment.POWER_WRIST::get, LodEquipment.WARGOD_CALLING::get, LodEquipment.PHANTOM_SHIELD::get, LodEquipment.DRAGON_SHIELD::get, LodEquipment.ANGEL_SCARF::get, LodEquipment.ULTIMATE_WARGOD::get));
  public static final RegistryDelegate<ShopStruct40> LOHAN_ITEM_SHOP = SHOP_REGISTRAR.register("lohan_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.SPINNING_GALE::get, LodItems.GUSHING_MAGMA::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> KAZAS_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("kazas_equipment_shop", () -> new ShopStruct40(0, LodEquipment.HEAT_BLADE::get, LodEquipment.LONG_BOW::get, LodEquipment.ARMET::get, LodEquipment.IRON_KNEEPIECE::get));
  public static final RegistryDelegate<ShopStruct40> KAZAS_FORT_ITEM_SHOP = SHOP_REGISTRAR.register("kazas_fort_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.DARK_MIST::get, LodItems.FATAL_BLIZZARD::get));
  public static final RegistryDelegate<ShopStruct40> FLETZ_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("fletz_equipment_shop", () -> new ShopStruct40(0, LodEquipment.SHADOW_CUTTER::get, LodEquipment.CHAIN_MAIL::get, LodEquipment.SOFT_BOOTS::get, LodEquipment.POISON_GUARD::get, LodEquipment.ACTIVE_RING::get, LodEquipment.PROTECTOR::get, LodEquipment.PANIC_GUARD::get, LodEquipment.STUN_GUARD::get, LodEquipment.BRAVERY_AMULET::get, LodEquipment.MAGIC_EGO_BELL::get, LodEquipment.POWER_WRIST::get, LodEquipment.KNIGHT_SHIELD::get, LodEquipment.WARGOD_CALLING::get));
  public static final RegistryDelegate<ShopStruct40> FLETZ_ITEM_SHOP = SHOP_REGISTRAR.register("fletz_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.TRANS_LIGHT::get, LodItems.BLACK_RAIN::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> DONAU_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("donau_equipment_shop", () -> new ShopStruct40(0, LodEquipment.SILVER_VEST::get, LodEquipment.TIARA::get));
  public static final RegistryDelegate<ShopStruct40> DONAU_ITEM_SHOP = SHOP_REGISTRAR.register("donau_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.RAVE_TWISTER::get));
  public static final RegistryDelegate<ShopStruct40> QUEEN_FURY_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("queen_fury_equipment_shop", () -> new ShopStruct40(0, LodEquipment.GLAIVE::get, LodEquipment.BEAST_FANG::get, LodEquipment.WARRIOR_DRESS::get, LodEquipment.STUN_GUARD::get, LodEquipment.MAGIC_EGO_BELL::get));
  public static final RegistryDelegate<ShopStruct40> QUEEN_FURY_ITEM_SHOP = SHOP_REGISTRAR.register("queen_fury_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.TRANS_LIGHT::get, LodItems.DANCING_RAY::get));
  public static final RegistryDelegate<ShopStruct40> FUENO_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("fueno_equipment_shop", () -> new ShopStruct40(0, LodEquipment.FALCHION::get, LodEquipment.BEMUSING_ARROW::get, LodEquipment.MORNING_STAR::get, LodEquipment.PLATE_MAIL::get, LodEquipment.SPARKLE_DRESS::get, LodEquipment.KNIGHT_HELM::get));
  public static final RegistryDelegate<ShopStruct40> FUENO_ITEM_SHOP = SHOP_REGISTRAR.register("fueno_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.CHARM_POTION::get, LodItems.BURN_OUT::get, LodItems.GUSHING_MAGMA::get));
  public static final RegistryDelegate<ShopStruct40> FURNI_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("furni_equipment_shop", () -> new ShopStruct40(0, LodEquipment.DANCING_DAGGER::get, LodEquipment.GIGANTO_HELM::get, LodEquipment.COMBAT_SHOES::get, LodEquipment.DESTONE_AMULET::get, LodEquipment.ATTACK_BADGE::get, LodEquipment.ELUDE_CLOAK::get));
  public static final RegistryDelegate<ShopStruct40> FURNI_ITEM_SHOP = SHOP_REGISTRAR.register("furni_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.DEPETRIFIER::get, LodItems.THUNDERBOLT::get));
  public static final RegistryDelegate<ShopStruct40> DENINGRAD_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("deningrad_equipment_shop", () -> new ShopStruct40(0, LodEquipment.TOMAHAWK::get, LodEquipment.SPEAR_OF_TERROR::get, LodEquipment.DIAMOND_CLAW::get, LodEquipment.BREAST_PLATE::get, LodEquipment.MASTERS_VEST::get, LodEquipment.SOUL_HEADBAND::get, LodEquipment.JEWELED_CROWN::get, LodEquipment.STARDUST_BOOTS::get, LodEquipment.PROTECTOR::get, LodEquipment.BRAVERY_AMULET::get, LodEquipment.DESTONE_AMULET::get, LodEquipment.ARMOR_OF_LEGEND::get));
  public static final RegistryDelegate<ShopStruct40> DENINGRAD_ITEM_SHOP = SHOP_REGISTRAR.register("deningrad_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.DEPETRIFIER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.SPARK_NET::get, LodItems.THUNDERBOLT::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> WINGLY_FOREST_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("wingly_forest_equipment_shop", () -> new ShopStruct40(0, LodEquipment.WAR_HAMMER::get, LodEquipment.MAGICAL_RING::get, LodEquipment.SPIRITUAL_RING::get, LodEquipment.SPIRIT_CLOAK::get));
  public static final RegistryDelegate<ShopStruct40> WINGLY_FOREST_ITEM_SHOP = SHOP_REGISTRAR.register("wingly_forest_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.SUN_RHAPSODY::get, LodItems.HEALING_BREEZE::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.DARK_MIST::get, LodItems.BLACK_RAIN::get));
  public static final RegistryDelegate<ShopStruct40> VELLWEB_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("vellweb_equipment_shop", () -> new ShopStruct40(0, LodEquipment.PARTISAN::get, LodEquipment.HEAVY_MACE::get, LodEquipment.GIGANTO_ARMOR::get, LodEquipment.ENERGY_GIRDLE::get, LodEquipment.GIGANTO_RING::get));
  public static final RegistryDelegate<ShopStruct40> VELLWEB_ITEM_SHOP = SHOP_REGISTRAR.register("vellweb_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> ULARA_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("ulara_equipment_shop", () -> new ShopStruct40(0, LodEquipment.FAIRY_SWORD::get, LodEquipment.ARROW_OF_FORCE::get, LodEquipment.THUNDER_FIST::get, LodEquipment.MAGICAL_GREAVES::get, LodEquipment.MAGICAL_RING::get, LodEquipment.SPIRITUAL_RING::get, LodEquipment.ELUDE_CLOAK::get, LodEquipment.SPIRIT_CLOAK::get, LodEquipment.SAGES_CLOAK::get));
  public static final RegistryDelegate<ShopStruct40> ULARA_ITEM_SHOP = SHOP_REGISTRAR.register("ulara_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.CHARM_POTION::get, LodItems.PANIC_BELL::get, LodItems.STUNNING_HAMMER::get, LodItems.POISON_NEEDLE::get, LodItems.MIDNIGHT_TERROR::get, LodItems.ATTACK_BALL::get, LodItems.RECOVERY_BALL::get));
  public static final RegistryDelegate<ShopStruct40> ROUGE_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("rouge_equipment_shop", () -> new ShopStruct40(0, LodEquipment.ATTACK_BADGE::get, LodEquipment.GUARD_BADGE::get, LodEquipment.GIGANTO_RING::get));
  public static final RegistryDelegate<ShopStruct40> ROUGE_ITEM_SHOP = SHOP_REGISTRAR.register("rouge_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.PANIC_BELL::get));
  public static final RegistryDelegate<ShopStruct40> MOON_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("moon_equipment_shop", () -> new ShopStruct40(0, LodEquipment.CLAYMORE::get, LodEquipment.HALBERD::get, LodEquipment.BASHER::get, LodEquipment.DESTROYER_MACE::get, LodEquipment.RED_DG_ARMOR::get, LodEquipment.JADE_DG_ARMOR::get, LodEquipment.GOLD_DG_ARMOR::get, LodEquipment.VIOLET_DG_ARMOR::get, LodEquipment.SILVER_DG_ARMOR::get, LodEquipment.DARK_DG_ARMOR::get, LodEquipment.BLUE_DG_ARMOR::get, LodEquipment.MAGICAL_RING::get, LodEquipment.SPIRITUAL_RING::get, LodEquipment.ATTACK_BADGE::get, LodEquipment.GUARD_BADGE::get, LodEquipment.GIGANTO_RING::get));
  public static final RegistryDelegate<ShopStruct40> MOON_ITEM_SHOP = SHOP_REGISTRAR.register("moon_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.DEPETRIFIER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.PANIC_BELL::get, LodItems.POISON_NEEDLE::get));
  public static final RegistryDelegate<ShopStruct40> HELLENA_01_ITEM_SHOP = SHOP_REGISTRAR.register("hellena_01_item_shop", () -> new ShopStruct40(3, LodItems.HEALING_POTION::get, LodItems.ANGELS_PRAYER::get, LodItems.SPARK_NET::get));
  public static final RegistryDelegate<ShopStruct40> KASHUA_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("kashua_equipment_shop", () -> new ShopStruct40(0, LodEquipment.MIND_CRUSH::get, LodEquipment.BATTLE_AXE::get, LodEquipment.FLAMBERGE::get, LodEquipment.VIRULENT_ARROW::get, LodEquipment.SAINT_ARMOR::get, LodEquipment.ROBE::get, LodEquipment.GUARD_BADGE::get));
  public static final RegistryDelegate<ShopStruct40> KASHUA_ITEM_SHOP = SHOP_REGISTRAR.register("kashua_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.HEALING_BREEZE::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.BODY_PURIFIER::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> FLETZ_ACCESSORY_SHOP = SHOP_REGISTRAR.register("fletz_accessory_shop", () -> new ShopStruct40(0, LodEquipment.RUBY_RING::get, LodEquipment.SAPPHIRE_PIN::get, LodEquipment.EMERALD_EARRING::get, LodEquipment.PLATINUM_COLLAR::get));
  public static final RegistryDelegate<ShopStruct40> FOREST_ITEM_SHOP = SHOP_REGISTRAR.register("forest_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.BODY_PURIFIER::get, LodItems.BURN_OUT::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> KAZAS_FORT_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("kazas_fort_equipment_shop", () -> new ShopStruct40(0, LodEquipment.FAKE_POWER_WRIST::get, LodEquipment.FAKE_SHIELD::get));
  public static final RegistryDelegate<ShopStruct40> VOLCANO_ITEM_SHOP = SHOP_REGISTRAR.register("volcano_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_POTION::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.DANCING_RAY::get, LodItems.PELLET::get));
  public static final RegistryDelegate<ShopStruct40> ZENEBATOS_EQUIPMENT_SHOP = SHOP_REGISTRAR.register("zenebatos_equipment_shop", () -> new ShopStruct40(0, LodEquipment.GREAT_AXE::get, LodEquipment.GLADIUS::get, LodEquipment.RED_DG_ARMOR::get, LodEquipment.JADE_DG_ARMOR::get, LodEquipment.DARK_DG_ARMOR::get, LodEquipment.BLUE_DG_ARMOR::get, LodEquipment.PANIC_GUARD::get, LodEquipment.BRAVERY_AMULET::get, LodEquipment.DESTONE_AMULET::get));
  public static final RegistryDelegate<ShopStruct40> ZENEBATOS_ITEM_SHOP = SHOP_REGISTRAR.register("zenebatos_item_shop", () -> new ShopStruct40(1, LodItems.HEALING_FOG::get, LodItems.SUN_RHAPSODY::get, LodItems.HEALING_BREEZE::get, LodItems.ANGELS_PRAYER::get, LodItems.DEPETRIFIER::get, LodItems.MIND_PURIFIER::get, LodItems.BODY_PURIFIER::get, LodItems.CHARM_POTION::get));
  public static final RegistryDelegate<ShopStruct40> HELLENA_02_ITEM_SHOP = SHOP_REGISTRAR.register("hellena_02_item_shop", () -> new ShopStruct40(3, LodItems.HEALING_POTION::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get, LodItems.MIND_PURIFIER::get, LodItems.MIDNIGHT_TERROR::get, LodItems.THUNDERBOLT::get));
  public static final RegistryDelegate<ShopStruct40> UNKNOWN_SHOP_01 = SHOP_REGISTRAR.register("unknown_shop_01", () -> new ShopStruct40(0, LodItems.HEALING_POTION::get, LodItems.SUN_RHAPSODY::get, LodItems.ANGELS_PRAYER::get));
  public static final RegistryDelegate<ShopStruct40> EMPTY_SHOP = SHOP_REGISTRAR.register("empty_shop", () -> new ShopStruct40(0));

  static void register(final ShopRegistryEvent event) {
    SHOP_REGISTRAR.registryEvent(event);
  }
}
