package legend.game.wmap;

public enum WmapState {
  INIT_0,
  WAIT_FOR_MUSIC_TO_LOAD_1,
  INIT2_2,
  PLAY_3,
  TRANSITION_TO_SCREENS_4,
  RENDER_SCREENS_5,
  EXIT_SCREENS_6,
  TRANSITION_TO_SUBMAP_7,
  TRANSITION_TO_BATTLE_8,
  TRANSITION_TO_WORLD_MAP_9,
  _10,
  _11,
  _12,
  TRANSITION_TO_TITLE_13,
  LOAD_BACKGROUND_OBJ_14,
}
