name: Promote Devbuild

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The release version'
        required: true
        type: string

jobs:
  copy-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Fetch and Duplicate Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SRC_TAG: devbuild
          NEW_TAG: ${{ inputs.version }}
          NEW_NAME: Release ${{ inputs.version }}
        run: |
          echo "Downloading assets from release tag: $SRC_TAG..."
          mkdir -p ./release-assets
          gh release download "$SRC_TAG" --dir ./release-assets

          echo "Fetching release notes..."
          gh release view "$SRC_TAG" --json body --jq '.body' > release_notes.md

          echo "Creating new release '$NEW_NAME' with tag '$NEW_TAG'..."
          gh release create "$NEW_TAG" \
            --title "$NEW_NAME" \
            --notes-file release_notes.md \
            --draft

          echo "Uploading assets to the new release..."
          gh release upload "$NEW_TAG" ./release-assets/*
          echo "Bye now"
